name: Deploy WordPress Theme to Kinsta

on:
  push:
    branches: [main, staging, dev]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.STAGING_PORT }}
          TARGET: ${{ secrets.STAGING_DIR }}


      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.PRODUCTION_PORT }}
          TARGET: ${{ secrets.PRODUCTION_DIR }}

